# Generated by Django 5.1.2 on 2024-11-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_floor', models.IntegerField(verbose_name='Количество квартир на этаже')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('total_area', models.IntegerField(verbose_name='Общая площадь')),
                ('living_area', models.IntegerField(verbose_name='Жилая площадь')),
                ('kitchen_area', models.IntegerField(verbose_name='Площадь кухни')),
                ('is_balcony', models.BooleanField(verbose_name='Наличие балкона')),
                ('price_square', models.IntegerField(verbose_name='Цена за кв.м.')),
                ('price_flat', models.IntegerField(verbose_name='Цена за квартиру')),
            ],
        ),
    ]
