# Generated by Django 5.1.2 on 2024-11-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(max_length=100, null=True, verbose_name='Планировка')),
                ('rooms', models.IntegerField(null=True, verbose_name='Количество комнат')),
                ('total_area', models.IntegerField(null=True, verbose_name='Общая площадь')),
                ('living_area', models.IntegerField(null=True, verbose_name='Жилая площадь')),
                ('kitchen_area', models.IntegerField(null=True, verbose_name='Площадь кухни')),
                ('is_balcony', models.BooleanField(null=True, verbose_name='Наличие балкона')),
                ('price_square', models.IntegerField(null=True, verbose_name='Цена за кв.м.')),
                ('price_flat', models.IntegerField(null=True, verbose_name='Цена за квартиру')),
            ],
            options={
                'verbose_name': 'Тип квартиры',
                'verbose_name_plural': 'Типы квартир',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Проект жилого дома')),
                ('description', models.TextField(verbose_name='Описание домов проекта')),
                ('amount_floors', models.IntegerField(verbose_name='Количество этажей')),
                ('rating', models.CharField(max_length=1, verbose_name='Класс дома')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Эмблема проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True, verbose_name='Номер дома')),
                ('on_street', models.CharField(max_length=150, null=True, verbose_name='Адрес дома')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Изображение корпуса')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='realty.project', verbose_name='Проект дома')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='Секция')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='realty.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Секцию',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(null=True, verbose_name='Номер этажа')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='realty.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True, verbose_name='Номер квартиры')),
                ('on_sale', models.BooleanField(default=True, verbose_name='В продаже')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Изображение квартиры')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.apartmenttype', verbose_name='Тип квартиры')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.building', verbose_name='Корпус')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.floor', verbose_name='Этаж')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Квартиру',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'building'), name='unique_section_per_building'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('floor_number', 'section'), name='unique_floor_per_section'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('num', 'building'), name='unique_apartment_per_building'),
        ),
    ]
