# Generated by Django 5.1.2 on 2024-11-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_project_building_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='apartmenttype',
            options={'verbose_name': 'Тип квартиры', 'verbose_name_plural': 'Типы квартир'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секцию', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение квартиры'),
        ),
    ]
