# Generated by Django 5.1.2 on 2024-11-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_alter_apartment_options_alter_apartmenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение корпуса'),
        ),
    ]
