# Generated by Django 5.1.2 on 2024-11-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_floor_apartment_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='floor_num',
        ),
    ]
