# Generated by Django 5.1.2 on 2024-11-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_building_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Эмблема проекта'),
        ),
    ]
